### PR TITLE
Various enhancements made this week

### PR DESCRIPTION
**Pull request by mike-allaway**
List of changes made this week in this PR:

- Allow audio only for multiple choice options. Give a standard message, e.g. (Please play audio clip)
- Allow exercises to be marked as a test/formal assessment. These exercises won't allow students to check their score, see answers, have multiple attempts, etc.
- Give instant feedback to questions rather than manually having to check all scores at once. I.e. when an answer is given (such as clicking on a multiple choice option) show if it's correct/wrong
- Allow teachers to explain correct answers with text-based feedback. When students click on 'show the answer' for each question in an exercise it will (optionally) also show the explanation feedback, including HTML links.
- Hide Theme from exercises in exercise list if they don't exist, as otherwise shows 'None' which isn't particularly user friendly
- Show the user's score on the exercise completed success page, for formats that support automatic marking
- Redesign the show answer icon to make more prominent
- etc.

### CODE REVIEW

**Comment by garciaay** [comment]
Hi Mike,
I am on annual leave this week, let me know if you want me to take a look when I get back.
Adrian

**Comment by mike-allaway** [comment]
> Hi Mike, I am on annual leave this week, let me know if you want me to take a look when I get back. Adrian

Sorry @garciaay I didn't realise - enjoy your AL! I'll pass the review to Cerys

**Review by afraz-ahmed — APPROVED** [review]
looks good

**Review by ceryslewis — APPROVED** [review]
All looks good

**Pull request merged**
